# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/bin:$HOME/local/ruby/bin:$HOME/local/perl/bin:$HOME/local/python/bin:$PATH:

export PATH

LANG=c
export LANG
export LC_ALL=en_US.UTF-8
